[project]
name = "hyperdrive-ann"
version = "0.1.0"
description = "GPU-accelerated approximate nearest neighbor search engine"
readme = "README.md"
requires-python = ">=3.8"

[dependencies]
# Core dependencies for optional Python bindings
pybind11 = {version = "^2.11.0", optional = true}
numpy = {version = "^1.21.0", optional = true}

[optional-dependencies]
python = ["pybind11", "numpy"]

[build-system]
requires = ["cmake>=3.20", "ninja"]
build-backend = "cmake"

[tool.uv]
dev-dependencies = []
